# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  phpunit:
    docker:
      - image: circleci/php:7.0-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_PASSWORD: shopware
          MYSQL_USER: shopware
          MYSQL_DATABASE: shopware
          MYSQL_ROOT_PASSWORD: shopware
    environment:
      SHOPWARE_VERSION: "5.5"
      PLUGIN_NAME: "MltisafeMultiSafepayPayment"
    steps:
      - checkout
      - run:
          name: Install System Package
          command: |
            sudo apt update
            sudo apt install -y sendmail sendmail-bin libpng-dev ant
      - run:
          name: Install PHP extension
          command: |
            sudo docker-php-ext-install zip pdo_mysql gd
      - run:
          name: Permissions
          command: |
            cd /var/www/
            sudo chown -R circleci:circleci html
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s      #Download shopware in root and install dependencies
      - run:
          name: Download shopware
          command: |
            cd /var/www/html/
            git clone -b $SHOPWARE_VERSION --single-branch --depth=1 https://github.com/shopware/shopware.git .
      - restore_cache:
          key: -v3-{{ checksum "/var/www/html/composer.json"}}
      - run:
          name: Composer install
          command: |
            cd /var/www/html
            composer install --prefer-dist
      - save_cache:
          key: -v3-{{ checksum "/var/www/html/composer.json"}}
          paths:
            - /var/www/html/vendor
      - run:
          name: Permissions
          command: |
            cd /var/www/html
            sudo chmod -R 755 custom/plugins
            sudo chmod -R 755 engine/Shopware/Plugins/Community
            sudo chmod -R 755 files
            sudo chmod -R 755 media
            sudo chmod -R 755 var
            sudo chmod -R 755 web
      - run:
          name: Install Shopware
          command: |
            cd /var/www/html/build
            mv build.properties.dist build.properties
            ant write-properties -Dapp.host=shopware.docker  -Ddb.name=shopware -Ddb.host=127.0.0.1 -Ddb.user=shopware -Ddb.password=shopware
            ant build-unit
      - run:
          name: Install Plugin
          command: |
            mkdir -p /var/www/html/custom/plugins/$PLUGIN_NAME
            mv * /var/www/html/custom/plugins/$PLUGIN_NAME
            cd /var/www/html
            bin/console sw:plugin:refresh
            bin/console sw:plugin:install $PLUGIN_NAME
            bin/console sw:plugin:activate $PLUGIN_NAME --clear-cache
            bin/console sw:plugin:refresh
            bin/console sw:generate:attributes
            bin/console orm:generate:proxies
      - run:
          name: Run PHPUnit
          command: |
            cd /var/www/html
            ./vendor/bin/phpunit --configuration ./custom/plugins/$PLUGIN_NAME/phpunit.xml.dist ./custom/plugins/$PLUGIN_NAME/
  codesniffer:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Move project
          command: mv * /var/www/html
      - restore_cache:
          key: -v1-{{ checksum "/var/www/html/composer.json"}}
      - run:
          name: Composer install
          command: |
            cd /var/www/html
            composer install --prefer-dist
      - save_cache:
          key: -v1-{{ checksum "/var/www/html/composer.json"}}
          paths:
            - /var/www/html/vendor
      - run:
          name: Run Code Sniffer
          command: |
            cd /var/www/html
            vendor/bin/phpcs --ignore=*/vendor/* --standard=phpcs.ruleset.xml -n /var/www/html
workflows:
  version: 2
  default_check:
    jobs:
      - codesniffer
      - phpunit